import requests
def login_user(): 
  headers={"authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjY3NzExNzIuMjMxNTc2LCJleHAiOjE2OTgzOTcxNzIuMjMxNTc2LCJ1c2VyX2lkIjoiNWEzODQxMDMtZmIxMy00NDQ5LTk1MDktYTA0NWMxZjU1MzgxIiwiZW1haWwiOiJndWVzdC41YTM4NDEwMy1mYjEzLTQ0NDktOTUwOS1hMDQ1YzFmNTUzODFAYnl0ZWxlYXJuLmFpIiwiZGlzcGxheV9uYW1lIjoidXNlciIsImZ1bGxfbmFtZSI6IkRFRkFVTFRfRlVMTF9OQU1FIiwicHJvZmlsZV9pbWFnZSI6bnVsbCwiZGVmYXVsdF9yb2xlIjoiZ3Vlc3RfdXNlciIsImltcGVyc29uYXRpbmciOmZhbHNlLCJpbXBlcnNvbmF0b3JfdXNlcl9pZCI6bnVsbCwicm9sZXMiOlsiZ3Vlc3RfdXNlciJdLCJzZXNzaW9uX2lkIjoic2Vzc2lvbl81NzA0MzkyMi1iOGE5LTRkNzUtYjZmNS1kMjQ5NWMzOGE2YzAiLCJjbGFzc19saXN0IjpbXX0.ZvyO-OveCS-vGl99Iv6GVkiTYbDQJJwlodIYeldLtVJ-j_TKduQY-dx-qeRaL31gU25VJ-vCZi00NMUFfcNtutglpuABCr8gkEf9NPa4nl6Au6oHTxzRrD2D81_TZZcaAvFoAkeNDVk--J_utOR7ywYDdoCCjynYJNWrc_4tTXANayXjyM6kOpcbKmmgT_UfhohJc7UaHBljGskeumfNCqgTyIF9tTHu70S70jba_X2GcRxDp4Obn8XIrMphUmS0Vb9S2G9gyGYVsIyooTq-8OXaAiHIAufUvFSKTNuDIKzQEklUSCIVg1VhxzfZKzbVezF3NErpZ6TZDT4gWpVlIWefrHHuXBPCWcR3G7Ni21csjv9Y5Fi6_rkv5ZZ6ChbHniI5d6klbaHaf1OPBsqbM9y5sJLC8A9BfLrFxxScJW8fQFZ7JhZRjPGe2tLeFdozd_AcE0fRXqwOwDFadX1CI9lpnyOj_NX99TWREPnz_65QNVf1Z28kV6wRzFuqP1xjTIoVUsFmDBsuLzmhDxbWSuMvj_mqmTNCHsRa-1j3NPdgw8uG0cj43Bm3L6FwT2mT-KQKVtDZvn7wJorSmZDMNvaZhfQz3NOt3bZvEXs_cSRIfDVEeOQt-Z59CCFfTaGmZwbrqZ4PPPw-iIgIds5yPGqaMmiwHe6RPwM1Ldf1Rh0"}
  r=requests.post(url="https://preproduserapi.bytelearn.ai/api/v1/user/login", headers=headers, json={"email": "sagar.sehgal@bytelearn.ai", "password":"password" , "provider":"local"}) 
  print(r.text)
  print(r.status_code)
  if r.status_code !=200:
    return [False,r.status_code,r.json()]
      
  return [True,r.status_code,r.json()]


login_user()
